/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 ./public/tv-scene.glb --transform 
Files: ./public/tv-scene.glb [1.79MB] > C:\Users\Sudeepto\Desktop\tv-scene\tv-scene-transformed.glb [191.01KB] (89%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function TVScene(props) {
  const { nodes, materials } = useGLTF('/tv-scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.tv.geometry} material={materials.Default} scale={0.005} />
      <mesh geometry={nodes.screen.geometry} material={materials.Light} scale={0.005} />
    </group>
  )
}

useGLTF.preload('/tv-scene-transformed.glb')
