/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 ./public/tv-scene.glb --transform 
Files: ./public/tv-scene.glb [1.79MB] > C:\Users\Sudeepto\Desktop\tv-scene\tv-scene-transformed.glb [191.01KB] (89%)
*/

import React, { useRef } from 'react'
import { useGLTF, useVideoTexture } from '@react-three/drei'
import * as THREE from 'three'

export function TVScene(props) {
  const { nodes, materials } = useGLTF('/tv-scene-transformed.glb')

  const videoTexture = useVideoTexture('/vid.mp4')
  videoTexture.flipY = false

  const newMaterial = new THREE.MeshBasicMaterial({
		map:videoTexture
	})

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.tv.geometry} material={materials.Default} scale={0.005} />
      <mesh geometry={nodes.screen.geometry} material={newMaterial} scale={0.005} />
    </group>
  )
}

useGLTF.preload('/tv-scene-transformed.glb')
